// proto/interview.proto
// protoc --go_out=. --go-grpc_out=. proto/interview.proto 2>&1

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: proto/interview.proto

package interview

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InterviewService_GetInterview_FullMethodName          = "/interview.InterviewService/GetInterview"
	InterviewService_CreateInterview_FullMethodName       = "/interview.InterviewService/CreateInterview"
	InterviewService_UpdateInterview_FullMethodName       = "/interview.InterviewService/UpdateInterview"
	InterviewService_UpdateInterviewStatus_FullMethodName = "/interview.InterviewService/UpdateInterviewStatus"
	InterviewService_ListInterviews_FullMethodName        = "/interview.InterviewService/ListInterviews"
)

// InterviewServiceClient is the client API for InterviewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InterviewService provides gRPC methods for interview management
type InterviewServiceClient interface {
	GetInterview(ctx context.Context, in *GetInterviewRequest, opts ...grpc.CallOption) (*Interview, error)
	CreateInterview(ctx context.Context, in *CreateInterviewRequest, opts ...grpc.CallOption) (*Interview, error)
	UpdateInterview(ctx context.Context, in *UpdateInterviewRequest, opts ...grpc.CallOption) (*Interview, error)
	UpdateInterviewStatus(ctx context.Context, in *UpdateInterviewStatusRequest, opts ...grpc.CallOption) (*Interview, error)
	ListInterviews(ctx context.Context, in *ListInterviewsRequest, opts ...grpc.CallOption) (*ListInterviewsResponse, error)
}

type interviewServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInterviewServiceClient(cc grpc.ClientConnInterface) InterviewServiceClient {
	return &interviewServiceClient{cc}
}

func (c *interviewServiceClient) GetInterview(ctx context.Context, in *GetInterviewRequest, opts ...grpc.CallOption) (*Interview, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Interview)
	err := c.cc.Invoke(ctx, InterviewService_GetInterview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interviewServiceClient) CreateInterview(ctx context.Context, in *CreateInterviewRequest, opts ...grpc.CallOption) (*Interview, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Interview)
	err := c.cc.Invoke(ctx, InterviewService_CreateInterview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interviewServiceClient) UpdateInterview(ctx context.Context, in *UpdateInterviewRequest, opts ...grpc.CallOption) (*Interview, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Interview)
	err := c.cc.Invoke(ctx, InterviewService_UpdateInterview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interviewServiceClient) UpdateInterviewStatus(ctx context.Context, in *UpdateInterviewStatusRequest, opts ...grpc.CallOption) (*Interview, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Interview)
	err := c.cc.Invoke(ctx, InterviewService_UpdateInterviewStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interviewServiceClient) ListInterviews(ctx context.Context, in *ListInterviewsRequest, opts ...grpc.CallOption) (*ListInterviewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInterviewsResponse)
	err := c.cc.Invoke(ctx, InterviewService_ListInterviews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InterviewServiceServer is the server API for InterviewService service.
// All implementations must embed UnimplementedInterviewServiceServer
// for forward compatibility.
//
// InterviewService provides gRPC methods for interview management
type InterviewServiceServer interface {
	GetInterview(context.Context, *GetInterviewRequest) (*Interview, error)
	CreateInterview(context.Context, *CreateInterviewRequest) (*Interview, error)
	UpdateInterview(context.Context, *UpdateInterviewRequest) (*Interview, error)
	UpdateInterviewStatus(context.Context, *UpdateInterviewStatusRequest) (*Interview, error)
	ListInterviews(context.Context, *ListInterviewsRequest) (*ListInterviewsResponse, error)
	mustEmbedUnimplementedInterviewServiceServer()
}

// UnimplementedInterviewServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInterviewServiceServer struct{}

func (UnimplementedInterviewServiceServer) GetInterview(context.Context, *GetInterviewRequest) (*Interview, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInterview not implemented")
}
func (UnimplementedInterviewServiceServer) CreateInterview(context.Context, *CreateInterviewRequest) (*Interview, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInterview not implemented")
}
func (UnimplementedInterviewServiceServer) UpdateInterview(context.Context, *UpdateInterviewRequest) (*Interview, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateInterview not implemented")
}
func (UnimplementedInterviewServiceServer) UpdateInterviewStatus(context.Context, *UpdateInterviewStatusRequest) (*Interview, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateInterviewStatus not implemented")
}
func (UnimplementedInterviewServiceServer) ListInterviews(context.Context, *ListInterviewsRequest) (*ListInterviewsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInterviews not implemented")
}
func (UnimplementedInterviewServiceServer) mustEmbedUnimplementedInterviewServiceServer() {}
func (UnimplementedInterviewServiceServer) testEmbeddedByValue()                          {}

// UnsafeInterviewServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InterviewServiceServer will
// result in compilation errors.
type UnsafeInterviewServiceServer interface {
	mustEmbedUnimplementedInterviewServiceServer()
}

func RegisterInterviewServiceServer(s grpc.ServiceRegistrar, srv InterviewServiceServer) {
	// If the following call panics, it indicates UnimplementedInterviewServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InterviewService_ServiceDesc, srv)
}

func _InterviewService_GetInterview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInterviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterviewServiceServer).GetInterview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterviewService_GetInterview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterviewServiceServer).GetInterview(ctx, req.(*GetInterviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterviewService_CreateInterview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInterviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterviewServiceServer).CreateInterview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterviewService_CreateInterview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterviewServiceServer).CreateInterview(ctx, req.(*CreateInterviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterviewService_UpdateInterview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInterviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterviewServiceServer).UpdateInterview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterviewService_UpdateInterview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterviewServiceServer).UpdateInterview(ctx, req.(*UpdateInterviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterviewService_UpdateInterviewStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInterviewStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterviewServiceServer).UpdateInterviewStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterviewService_UpdateInterviewStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterviewServiceServer).UpdateInterviewStatus(ctx, req.(*UpdateInterviewStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterviewService_ListInterviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInterviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterviewServiceServer).ListInterviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterviewService_ListInterviews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterviewServiceServer).ListInterviews(ctx, req.(*ListInterviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InterviewService_ServiceDesc is the grpc.ServiceDesc for InterviewService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InterviewService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interview.InterviewService",
	HandlerType: (*InterviewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInterview",
			Handler:    _InterviewService_GetInterview_Handler,
		},
		{
			MethodName: "CreateInterview",
			Handler:    _InterviewService_CreateInterview_Handler,
		},
		{
			MethodName: "UpdateInterview",
			Handler:    _InterviewService_UpdateInterview_Handler,
		},
		{
			MethodName: "UpdateInterviewStatus",
			Handler:    _InterviewService_UpdateInterviewStatus_Handler,
		},
		{
			MethodName: "ListInterviews",
			Handler:    _InterviewService_ListInterviews_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/interview.proto",
}

const (
	FeedbackService_GetFeedback_FullMethodName            = "/interview.FeedbackService/GetFeedback"
	FeedbackService_GetFeedbackByInterview_FullMethodName = "/interview.FeedbackService/GetFeedbackByInterview"
	FeedbackService_CreateFeedback_FullMethodName         = "/interview.FeedbackService/CreateFeedback"
	FeedbackService_UpdateFeedback_FullMethodName         = "/interview.FeedbackService/UpdateFeedback"
)

// FeedbackServiceClient is the client API for FeedbackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FeedbackService provides gRPC methods for feedback management
type FeedbackServiceClient interface {
	GetFeedback(ctx context.Context, in *GetFeedbackRequest, opts ...grpc.CallOption) (*Feedback, error)
	GetFeedbackByInterview(ctx context.Context, in *GetFeedbackByInterviewRequest, opts ...grpc.CallOption) (*Feedback, error)
	CreateFeedback(ctx context.Context, in *CreateFeedbackRequest, opts ...grpc.CallOption) (*Feedback, error)
	UpdateFeedback(ctx context.Context, in *UpdateFeedbackRequest, opts ...grpc.CallOption) (*Feedback, error)
}

type feedbackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFeedbackServiceClient(cc grpc.ClientConnInterface) FeedbackServiceClient {
	return &feedbackServiceClient{cc}
}

func (c *feedbackServiceClient) GetFeedback(ctx context.Context, in *GetFeedbackRequest, opts ...grpc.CallOption) (*Feedback, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Feedback)
	err := c.cc.Invoke(ctx, FeedbackService_GetFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackServiceClient) GetFeedbackByInterview(ctx context.Context, in *GetFeedbackByInterviewRequest, opts ...grpc.CallOption) (*Feedback, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Feedback)
	err := c.cc.Invoke(ctx, FeedbackService_GetFeedbackByInterview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackServiceClient) CreateFeedback(ctx context.Context, in *CreateFeedbackRequest, opts ...grpc.CallOption) (*Feedback, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Feedback)
	err := c.cc.Invoke(ctx, FeedbackService_CreateFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackServiceClient) UpdateFeedback(ctx context.Context, in *UpdateFeedbackRequest, opts ...grpc.CallOption) (*Feedback, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Feedback)
	err := c.cc.Invoke(ctx, FeedbackService_UpdateFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeedbackServiceServer is the server API for FeedbackService service.
// All implementations must embed UnimplementedFeedbackServiceServer
// for forward compatibility.
//
// FeedbackService provides gRPC methods for feedback management
type FeedbackServiceServer interface {
	GetFeedback(context.Context, *GetFeedbackRequest) (*Feedback, error)
	GetFeedbackByInterview(context.Context, *GetFeedbackByInterviewRequest) (*Feedback, error)
	CreateFeedback(context.Context, *CreateFeedbackRequest) (*Feedback, error)
	UpdateFeedback(context.Context, *UpdateFeedbackRequest) (*Feedback, error)
	mustEmbedUnimplementedFeedbackServiceServer()
}

// UnimplementedFeedbackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFeedbackServiceServer struct{}

func (UnimplementedFeedbackServiceServer) GetFeedback(context.Context, *GetFeedbackRequest) (*Feedback, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeedback not implemented")
}
func (UnimplementedFeedbackServiceServer) GetFeedbackByInterview(context.Context, *GetFeedbackByInterviewRequest) (*Feedback, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeedbackByInterview not implemented")
}
func (UnimplementedFeedbackServiceServer) CreateFeedback(context.Context, *CreateFeedbackRequest) (*Feedback, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFeedback not implemented")
}
func (UnimplementedFeedbackServiceServer) UpdateFeedback(context.Context, *UpdateFeedbackRequest) (*Feedback, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFeedback not implemented")
}
func (UnimplementedFeedbackServiceServer) mustEmbedUnimplementedFeedbackServiceServer() {}
func (UnimplementedFeedbackServiceServer) testEmbeddedByValue()                         {}

// UnsafeFeedbackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeedbackServiceServer will
// result in compilation errors.
type UnsafeFeedbackServiceServer interface {
	mustEmbedUnimplementedFeedbackServiceServer()
}

func RegisterFeedbackServiceServer(s grpc.ServiceRegistrar, srv FeedbackServiceServer) {
	// If the following call panics, it indicates UnimplementedFeedbackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FeedbackService_ServiceDesc, srv)
}

func _FeedbackService_GetFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).GetFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedbackService_GetFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).GetFeedback(ctx, req.(*GetFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedbackService_GetFeedbackByInterview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedbackByInterviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).GetFeedbackByInterview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedbackService_GetFeedbackByInterview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).GetFeedbackByInterview(ctx, req.(*GetFeedbackByInterviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedbackService_CreateFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).CreateFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedbackService_CreateFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).CreateFeedback(ctx, req.(*CreateFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedbackService_UpdateFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).UpdateFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedbackService_UpdateFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).UpdateFeedback(ctx, req.(*UpdateFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FeedbackService_ServiceDesc is the grpc.ServiceDesc for FeedbackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeedbackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interview.FeedbackService",
	HandlerType: (*FeedbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFeedback",
			Handler:    _FeedbackService_GetFeedback_Handler,
		},
		{
			MethodName: "GetFeedbackByInterview",
			Handler:    _FeedbackService_GetFeedbackByInterview_Handler,
		},
		{
			MethodName: "CreateFeedback",
			Handler:    _FeedbackService_CreateFeedback_Handler,
		},
		{
			MethodName: "UpdateFeedback",
			Handler:    _FeedbackService_UpdateFeedback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/interview.proto",
}

const (
	PortfolioService_GetPortfolio_FullMethodName    = "/interview.PortfolioService/GetPortfolio"
	PortfolioService_CreatePortfolio_FullMethodName = "/interview.PortfolioService/CreatePortfolio"
	PortfolioService_UpdatePortfolio_FullMethodName = "/interview.PortfolioService/UpdatePortfolio"
	PortfolioService_ListPortfolios_FullMethodName  = "/interview.PortfolioService/ListPortfolios"
)

// PortfolioServiceClient is the client API for PortfolioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PortfolioService provides gRPC methods for portfolio management
type PortfolioServiceClient interface {
	GetPortfolio(ctx context.Context, in *GetPortfolioRequest, opts ...grpc.CallOption) (*Portfolio, error)
	CreatePortfolio(ctx context.Context, in *CreatePortfolioRequest, opts ...grpc.CallOption) (*Portfolio, error)
	UpdatePortfolio(ctx context.Context, in *UpdatePortfolioRequest, opts ...grpc.CallOption) (*Portfolio, error)
	ListPortfolios(ctx context.Context, in *ListPortfoliosRequest, opts ...grpc.CallOption) (*ListPortfoliosResponse, error)
}

type portfolioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPortfolioServiceClient(cc grpc.ClientConnInterface) PortfolioServiceClient {
	return &portfolioServiceClient{cc}
}

func (c *portfolioServiceClient) GetPortfolio(ctx context.Context, in *GetPortfolioRequest, opts ...grpc.CallOption) (*Portfolio, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Portfolio)
	err := c.cc.Invoke(ctx, PortfolioService_GetPortfolio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) CreatePortfolio(ctx context.Context, in *CreatePortfolioRequest, opts ...grpc.CallOption) (*Portfolio, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Portfolio)
	err := c.cc.Invoke(ctx, PortfolioService_CreatePortfolio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) UpdatePortfolio(ctx context.Context, in *UpdatePortfolioRequest, opts ...grpc.CallOption) (*Portfolio, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Portfolio)
	err := c.cc.Invoke(ctx, PortfolioService_UpdatePortfolio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) ListPortfolios(ctx context.Context, in *ListPortfoliosRequest, opts ...grpc.CallOption) (*ListPortfoliosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPortfoliosResponse)
	err := c.cc.Invoke(ctx, PortfolioService_ListPortfolios_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortfolioServiceServer is the server API for PortfolioService service.
// All implementations must embed UnimplementedPortfolioServiceServer
// for forward compatibility.
//
// PortfolioService provides gRPC methods for portfolio management
type PortfolioServiceServer interface {
	GetPortfolio(context.Context, *GetPortfolioRequest) (*Portfolio, error)
	CreatePortfolio(context.Context, *CreatePortfolioRequest) (*Portfolio, error)
	UpdatePortfolio(context.Context, *UpdatePortfolioRequest) (*Portfolio, error)
	ListPortfolios(context.Context, *ListPortfoliosRequest) (*ListPortfoliosResponse, error)
	mustEmbedUnimplementedPortfolioServiceServer()
}

// UnimplementedPortfolioServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPortfolioServiceServer struct{}

func (UnimplementedPortfolioServiceServer) GetPortfolio(context.Context, *GetPortfolioRequest) (*Portfolio, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPortfolio not implemented")
}
func (UnimplementedPortfolioServiceServer) CreatePortfolio(context.Context, *CreatePortfolioRequest) (*Portfolio, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePortfolio not implemented")
}
func (UnimplementedPortfolioServiceServer) UpdatePortfolio(context.Context, *UpdatePortfolioRequest) (*Portfolio, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePortfolio not implemented")
}
func (UnimplementedPortfolioServiceServer) ListPortfolios(context.Context, *ListPortfoliosRequest) (*ListPortfoliosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPortfolios not implemented")
}
func (UnimplementedPortfolioServiceServer) mustEmbedUnimplementedPortfolioServiceServer() {}
func (UnimplementedPortfolioServiceServer) testEmbeddedByValue()                          {}

// UnsafePortfolioServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortfolioServiceServer will
// result in compilation errors.
type UnsafePortfolioServiceServer interface {
	mustEmbedUnimplementedPortfolioServiceServer()
}

func RegisterPortfolioServiceServer(s grpc.ServiceRegistrar, srv PortfolioServiceServer) {
	// If the following call panics, it indicates UnimplementedPortfolioServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PortfolioService_ServiceDesc, srv)
}

func _PortfolioService_GetPortfolio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPortfolioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetPortfolio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetPortfolio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetPortfolio(ctx, req.(*GetPortfolioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_CreatePortfolio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePortfolioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).CreatePortfolio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_CreatePortfolio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).CreatePortfolio(ctx, req.(*CreatePortfolioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_UpdatePortfolio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePortfolioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).UpdatePortfolio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_UpdatePortfolio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).UpdatePortfolio(ctx, req.(*UpdatePortfolioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_ListPortfolios_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPortfoliosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).ListPortfolios(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_ListPortfolios_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).ListPortfolios(ctx, req.(*ListPortfoliosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PortfolioService_ServiceDesc is the grpc.ServiceDesc for PortfolioService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortfolioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interview.PortfolioService",
	HandlerType: (*PortfolioServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPortfolio",
			Handler:    _PortfolioService_GetPortfolio_Handler,
		},
		{
			MethodName: "CreatePortfolio",
			Handler:    _PortfolioService_CreatePortfolio_Handler,
		},
		{
			MethodName: "UpdatePortfolio",
			Handler:    _PortfolioService_UpdatePortfolio_Handler,
		},
		{
			MethodName: "ListPortfolios",
			Handler:    _PortfolioService_ListPortfolios_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/interview.proto",
}
