// proto/interview.proto
// protoc --go_out=. --go-grpc_out=. proto/interview.proto 2>&1

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/interview.proto

package interview

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Interview represents an interview record
type Interview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ResumeId      string                 `protobuf:"bytes,2,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	Round         int32                  `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	Interviewer   string                 `protobuf:"bytes,4,opt,name=interviewer,proto3" json:"interviewer,omitempty"`
	ScheduledAt   int64                  `protobuf:"varint,5,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interview) Reset() {
	*x = Interview{}
	mi := &file_proto_interview_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interview) ProtoMessage() {}

func (x *Interview) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interview_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interview.ProtoReflect.Descriptor instead.
func (*Interview) Descriptor() ([]byte, []int) {
	return file_proto_interview_proto_rawDescGZIP(), []int{0}
}

func (x *Interview) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Interview) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

func (x *Interview) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *Interview) GetInterviewer() string {
	if x != nil {
		return x.Interviewer
	}
	return ""
}

func (x *Interview) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

func (x *Interview) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Interview) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Interview) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// Feedback represents interview feedback
type Feedback struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InterviewId    string                 `protobuf:"bytes,2,opt,name=interview_id,json=interviewId,proto3" json:"interview_id,omitempty"`
	Rating         int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Content        string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Recommendation string                 `protobuf:"bytes,5,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Feedback) Reset() {
	*x = Feedback{}
	mi := &file_proto_interview_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feedback) ProtoMessage() {}

func (x *Feedback) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interview_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feedback.ProtoReflect.Descriptor instead.
func (*Feedback) Descriptor() ([]byte, []int) {
	return file_proto_interview_proto_rawDescGZIP(), []int{1}
}

func (x *Feedback) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Feedback) GetInterviewId() string {
	if x != nil {
		return x.InterviewId
	}
	return ""
}

func (x *Feedback) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Feedback) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Feedback) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

func (x *Feedback) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// Portfolio represents a candidate's portfolio item
type Portfolio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ResumeId      string                 `protobuf:"bytes,2,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	FileUrl       string                 `protobuf:"bytes,4,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FileType      string                 `protobuf:"bytes,5,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Portfolio) Reset() {
	*x = Portfolio{}
	mi := &file_proto_interview_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Portfolio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Portfolio) ProtoMessage() {}

func (x *Portfolio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interview_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Portfolio.ProtoReflect.Descriptor instead.
func (*Portfolio) Descriptor() ([]byte, []int) {
	return file_proto_interview_proto_rawDescGZIP(), []int{2}
}

func (x *Portfolio) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Portfolio) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

func (x *Portfolio) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Portfolio) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *Portfolio) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *Portfolio) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// GetInterviewRequest
type GetInterviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInterviewRequest) Reset() {
	*x = GetInterviewRequest{}
	mi := &file_proto_interview_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInterviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInterviewRequest) ProtoMessage() {}

func (x *GetInterviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interview_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInterviewRequest.ProtoReflect.Descriptor instead.
func (*GetInterviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_interview_proto_rawDescGZIP(), []int{3}
}

func (x *GetInterviewRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// CreateInterviewRequest
type CreateInterviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResumeId      string                 `protobuf:"bytes,1,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	Round         int32                  `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Interviewer   string                 `protobuf:"bytes,3,opt,name=interviewer,proto3" json:"interviewer,omitempty"`
	ScheduledAt   int64                  `protobuf:"varint,4,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInterviewRequest) Reset() {
	*x = CreateInterviewRequest{}
	mi := &file_proto_interview_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInterviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInterviewRequest) ProtoMessage() {}

func (x *CreateInterviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interview_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInterviewRequest.ProtoReflect.Descriptor instead.
func (*CreateInterviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_interview_proto_rawDescGZIP(), []int{4}
}

func (x *CreateInterviewRequest) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

func (x *CreateInterviewRequest) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *CreateInterviewRequest) GetInterviewer() string {
	if x != nil {
		return x.Interviewer
	}
	return ""
}

func (x *CreateInterviewRequest) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

// UpdateInterviewRequest
type UpdateInterviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Round         int32                  `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Interviewer   string                 `protobuf:"bytes,3,opt,name=interviewer,proto3" json:"interviewer,omitempty"`
	ScheduledAt   int64                  `protobuf:"varint,4,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInterviewRequest) Reset() {
	*x = UpdateInterviewRequest{}
	mi := &file_proto_interview_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInterviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInterviewRequest) ProtoMessage() {}

func (x *UpdateInterviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interview_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInterviewRequest.ProtoReflect.Descriptor instead.
func (*UpdateInterviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_interview_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateInterviewRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateInterviewRequest) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *UpdateInterviewRequest) GetInterviewer() string {
	if x != nil {
		return x.Interviewer
	}
	return ""
}

func (x *UpdateInterviewRequest) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

// UpdateInterviewStatusRequest
type UpdateInterviewStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInterviewStatusRequest) Reset() {
	*x = UpdateInterviewStatusRequest{}
	mi := &file_proto_interview_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInterviewStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInterviewStatusRequest) ProtoMessage() {}

func (x *UpdateInterviewStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interview_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInterviewStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateInterviewStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_interview_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateInterviewStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateInterviewStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// ListInterviewsRequest
type ListInterviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ResumeId      string                 `protobuf:"bytes,4,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInterviewsRequest) Reset() {
	*x = ListInterviewsRequest{}
	mi := &file_proto_interview_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInterviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterviewsRequest) ProtoMessage() {}

func (x *ListInterviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interview_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInterviewsRequest.ProtoReflect.Descriptor instead.
func (*ListInterviewsRequest) Descriptor() ([]byte, []int) {
	return file_proto_interview_proto_rawDescGZIP(), []int{7}
}

func (x *ListInterviewsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListInterviewsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListInterviewsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListInterviewsRequest) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

// ListInterviewsResponse
type ListInterviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interviews    []*Interview           `protobuf:"bytes,1,rep,name=interviews,proto3" json:"interviews,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInterviewsResponse) Reset() {
	*x = ListInterviewsResponse{}
	mi := &file_proto_interview_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInterviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterviewsResponse) ProtoMessage() {}

func (x *ListInterviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interview_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInterviewsResponse.ProtoReflect.Descriptor instead.
func (*ListInterviewsResponse) Descriptor() ([]byte, []int) {
	return file_proto_interview_proto_rawDescGZIP(), []int{8}
}

func (x *ListInterviewsResponse) GetInterviews() []*Interview {
	if x != nil {
		return x.Interviews
	}
	return nil
}

func (x *ListInterviewsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// GetFeedbackRequest
type GetFeedbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedbackRequest) Reset() {
	*x = GetFeedbackRequest{}
	mi := &file_proto_interview_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedbackRequest) ProtoMessage() {}

func (x *GetFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interview_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedbackRequest.ProtoReflect.Descriptor instead.
func (*GetFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_proto_interview_proto_rawDescGZIP(), []int{9}
}

func (x *GetFeedbackRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetFeedbackByInterviewRequest
type GetFeedbackByInterviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterviewId   string                 `protobuf:"bytes,1,opt,name=interview_id,json=interviewId,proto3" json:"interview_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedbackByInterviewRequest) Reset() {
	*x = GetFeedbackByInterviewRequest{}
	mi := &file_proto_interview_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedbackByInterviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedbackByInterviewRequest) ProtoMessage() {}

func (x *GetFeedbackByInterviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interview_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedbackByInterviewRequest.ProtoReflect.Descriptor instead.
func (*GetFeedbackByInterviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_interview_proto_rawDescGZIP(), []int{10}
}

func (x *GetFeedbackByInterviewRequest) GetInterviewId() string {
	if x != nil {
		return x.InterviewId
	}
	return ""
}

// CreateFeedbackRequest
type CreateFeedbackRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InterviewId    string                 `protobuf:"bytes,1,opt,name=interview_id,json=interviewId,proto3" json:"interview_id,omitempty"`
	Rating         int32                  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Content        string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Recommendation string                 `protobuf:"bytes,4,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateFeedbackRequest) Reset() {
	*x = CreateFeedbackRequest{}
	mi := &file_proto_interview_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeedbackRequest) ProtoMessage() {}

func (x *CreateFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interview_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeedbackRequest.ProtoReflect.Descriptor instead.
func (*CreateFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_proto_interview_proto_rawDescGZIP(), []int{11}
}

func (x *CreateFeedbackRequest) GetInterviewId() string {
	if x != nil {
		return x.InterviewId
	}
	return ""
}

func (x *CreateFeedbackRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateFeedbackRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateFeedbackRequest) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

// UpdateFeedbackRequest
type UpdateFeedbackRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rating         int32                  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Content        string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Recommendation string                 `protobuf:"bytes,4,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateFeedbackRequest) Reset() {
	*x = UpdateFeedbackRequest{}
	mi := &file_proto_interview_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFeedbackRequest) ProtoMessage() {}

func (x *UpdateFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interview_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFeedbackRequest.ProtoReflect.Descriptor instead.
func (*UpdateFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_proto_interview_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateFeedbackRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFeedbackRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *UpdateFeedbackRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateFeedbackRequest) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

// GetPortfolioRequest
type GetPortfolioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioRequest) Reset() {
	*x = GetPortfolioRequest{}
	mi := &file_proto_interview_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioRequest) ProtoMessage() {}

func (x *GetPortfolioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interview_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioRequest.ProtoReflect.Descriptor instead.
func (*GetPortfolioRequest) Descriptor() ([]byte, []int) {
	return file_proto_interview_proto_rawDescGZIP(), []int{13}
}

func (x *GetPortfolioRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// CreatePortfolioRequest
type CreatePortfolioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResumeId      string                 `protobuf:"bytes,1,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	FileUrl       string                 `protobuf:"bytes,3,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FileType      string                 `protobuf:"bytes,4,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePortfolioRequest) Reset() {
	*x = CreatePortfolioRequest{}
	mi := &file_proto_interview_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePortfolioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePortfolioRequest) ProtoMessage() {}

func (x *CreatePortfolioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interview_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePortfolioRequest.ProtoReflect.Descriptor instead.
func (*CreatePortfolioRequest) Descriptor() ([]byte, []int) {
	return file_proto_interview_proto_rawDescGZIP(), []int{14}
}

func (x *CreatePortfolioRequest) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

func (x *CreatePortfolioRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePortfolioRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *CreatePortfolioRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

// UpdatePortfolioRequest
type UpdatePortfolioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	FileUrl       string                 `protobuf:"bytes,3,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FileType      string                 `protobuf:"bytes,4,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePortfolioRequest) Reset() {
	*x = UpdatePortfolioRequest{}
	mi := &file_proto_interview_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePortfolioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePortfolioRequest) ProtoMessage() {}

func (x *UpdatePortfolioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interview_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePortfolioRequest.ProtoReflect.Descriptor instead.
func (*UpdatePortfolioRequest) Descriptor() ([]byte, []int) {
	return file_proto_interview_proto_rawDescGZIP(), []int{15}
}

func (x *UpdatePortfolioRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePortfolioRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdatePortfolioRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *UpdatePortfolioRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

// ListPortfoliosRequest
type ListPortfoliosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	ResumeId      string                 `protobuf:"bytes,3,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPortfoliosRequest) Reset() {
	*x = ListPortfoliosRequest{}
	mi := &file_proto_interview_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPortfoliosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPortfoliosRequest) ProtoMessage() {}

func (x *ListPortfoliosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interview_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPortfoliosRequest.ProtoReflect.Descriptor instead.
func (*ListPortfoliosRequest) Descriptor() ([]byte, []int) {
	return file_proto_interview_proto_rawDescGZIP(), []int{16}
}

func (x *ListPortfoliosRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPortfoliosRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPortfoliosRequest) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

// ListPortfoliosResponse
type ListPortfoliosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Portfolios    []*Portfolio           `protobuf:"bytes,1,rep,name=portfolios,proto3" json:"portfolios,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPortfoliosResponse) Reset() {
	*x = ListPortfoliosResponse{}
	mi := &file_proto_interview_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPortfoliosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPortfoliosResponse) ProtoMessage() {}

func (x *ListPortfoliosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interview_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPortfoliosResponse.ProtoReflect.Descriptor instead.
func (*ListPortfoliosResponse) Descriptor() ([]byte, []int) {
	return file_proto_interview_proto_rawDescGZIP(), []int{17}
}

func (x *ListPortfoliosResponse) GetPortfolios() []*Portfolio {
	if x != nil {
		return x.Portfolios
	}
	return nil
}

func (x *ListPortfoliosResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_interview_proto protoreflect.FileDescriptor

const file_proto_interview_proto_rawDesc = "" +
	"\n" +
	"\x15proto/interview.proto\x12\tinterview\"\xe9\x01\n" +
	"\tInterview\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tresume_id\x18\x02 \x01(\tR\bresumeId\x12\x14\n" +
	"\x05round\x18\x03 \x01(\x05R\x05round\x12 \n" +
	"\vinterviewer\x18\x04 \x01(\tR\vinterviewer\x12!\n" +
	"\fscheduled_at\x18\x05 \x01(\x03R\vscheduledAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"\xb6\x01\n" +
	"\bFeedback\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\finterview_id\x18\x02 \x01(\tR\vinterviewId\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12&\n" +
	"\x0erecommendation\x18\x05 \x01(\tR\x0erecommendation\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"\xa5\x01\n" +
	"\tPortfolio\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tresume_id\x18\x02 \x01(\tR\bresumeId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x19\n" +
	"\bfile_url\x18\x04 \x01(\tR\afileUrl\x12\x1b\n" +
	"\tfile_type\x18\x05 \x01(\tR\bfileType\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"%\n" +
	"\x13GetInterviewRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x90\x01\n" +
	"\x16CreateInterviewRequest\x12\x1b\n" +
	"\tresume_id\x18\x01 \x01(\tR\bresumeId\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x05R\x05round\x12 \n" +
	"\vinterviewer\x18\x03 \x01(\tR\vinterviewer\x12!\n" +
	"\fscheduled_at\x18\x04 \x01(\x03R\vscheduledAt\"\x83\x01\n" +
	"\x16UpdateInterviewRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x05R\x05round\x12 \n" +
	"\vinterviewer\x18\x03 \x01(\tR\vinterviewer\x12!\n" +
	"\fscheduled_at\x18\x04 \x01(\x03R\vscheduledAt\"F\n" +
	"\x1cUpdateInterviewStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"}\n" +
	"\x15ListInterviewsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\tresume_id\x18\x04 \x01(\tR\bresumeId\"d\n" +
	"\x16ListInterviewsResponse\x124\n" +
	"\n" +
	"interviews\x18\x01 \x03(\v2\x14.interview.InterviewR\n" +
	"interviews\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"$\n" +
	"\x12GetFeedbackRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x1dGetFeedbackByInterviewRequest\x12!\n" +
	"\finterview_id\x18\x01 \x01(\tR\vinterviewId\"\x94\x01\n" +
	"\x15CreateFeedbackRequest\x12!\n" +
	"\finterview_id\x18\x01 \x01(\tR\vinterviewId\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x05R\x06rating\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12&\n" +
	"\x0erecommendation\x18\x04 \x01(\tR\x0erecommendation\"\x81\x01\n" +
	"\x15UpdateFeedbackRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x05R\x06rating\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12&\n" +
	"\x0erecommendation\x18\x04 \x01(\tR\x0erecommendation\"%\n" +
	"\x13GetPortfolioRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x83\x01\n" +
	"\x16CreatePortfolioRequest\x12\x1b\n" +
	"\tresume_id\x18\x01 \x01(\tR\bresumeId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x19\n" +
	"\bfile_url\x18\x03 \x01(\tR\afileUrl\x12\x1b\n" +
	"\tfile_type\x18\x04 \x01(\tR\bfileType\"v\n" +
	"\x16UpdatePortfolioRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x19\n" +
	"\bfile_url\x18\x03 \x01(\tR\afileUrl\x12\x1b\n" +
	"\tfile_type\x18\x04 \x01(\tR\bfileType\"e\n" +
	"\x15ListPortfoliosRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1b\n" +
	"\tresume_id\x18\x03 \x01(\tR\bresumeId\"d\n" +
	"\x16ListPortfoliosResponse\x124\n" +
	"\n" +
	"portfolios\x18\x01 \x03(\v2\x14.interview.PortfolioR\n" +
	"portfolios\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\x9f\x03\n" +
	"\x10InterviewService\x12D\n" +
	"\fGetInterview\x12\x1e.interview.GetInterviewRequest\x1a\x14.interview.Interview\x12J\n" +
	"\x0fCreateInterview\x12!.interview.CreateInterviewRequest\x1a\x14.interview.Interview\x12J\n" +
	"\x0fUpdateInterview\x12!.interview.UpdateInterviewRequest\x1a\x14.interview.Interview\x12V\n" +
	"\x15UpdateInterviewStatus\x12'.interview.UpdateInterviewStatusRequest\x1a\x14.interview.Interview\x12U\n" +
	"\x0eListInterviews\x12 .interview.ListInterviewsRequest\x1a!.interview.ListInterviewsResponse2\xbf\x02\n" +
	"\x0fFeedbackService\x12A\n" +
	"\vGetFeedback\x12\x1d.interview.GetFeedbackRequest\x1a\x13.interview.Feedback\x12W\n" +
	"\x16GetFeedbackByInterview\x12(.interview.GetFeedbackByInterviewRequest\x1a\x13.interview.Feedback\x12G\n" +
	"\x0eCreateFeedback\x12 .interview.CreateFeedbackRequest\x1a\x13.interview.Feedback\x12G\n" +
	"\x0eUpdateFeedback\x12 .interview.UpdateFeedbackRequest\x1a\x13.interview.Feedback2\xc7\x02\n" +
	"\x10PortfolioService\x12D\n" +
	"\fGetPortfolio\x12\x1e.interview.GetPortfolioRequest\x1a\x14.interview.Portfolio\x12J\n" +
	"\x0fCreatePortfolio\x12!.interview.CreatePortfolioRequest\x1a\x14.interview.Portfolio\x12J\n" +
	"\x0fUpdatePortfolio\x12!.interview.UpdatePortfolioRequest\x1a\x14.interview.Portfolio\x12U\n" +
	"\x0eListPortfolios\x12 .interview.ListPortfoliosRequest\x1a!.interview.ListPortfoliosResponseBBZ@github.com/example/ats-hr-interview/internal/shared/pb/interviewb\x06proto3"

var (
	file_proto_interview_proto_rawDescOnce sync.Once
	file_proto_interview_proto_rawDescData []byte
)

func file_proto_interview_proto_rawDescGZIP() []byte {
	file_proto_interview_proto_rawDescOnce.Do(func() {
		file_proto_interview_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_interview_proto_rawDesc), len(file_proto_interview_proto_rawDesc)))
	})
	return file_proto_interview_proto_rawDescData
}

var file_proto_interview_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_interview_proto_goTypes = []any{
	(*Interview)(nil),                     // 0: interview.Interview
	(*Feedback)(nil),                      // 1: interview.Feedback
	(*Portfolio)(nil),                     // 2: interview.Portfolio
	(*GetInterviewRequest)(nil),           // 3: interview.GetInterviewRequest
	(*CreateInterviewRequest)(nil),        // 4: interview.CreateInterviewRequest
	(*UpdateInterviewRequest)(nil),        // 5: interview.UpdateInterviewRequest
	(*UpdateInterviewStatusRequest)(nil),  // 6: interview.UpdateInterviewStatusRequest
	(*ListInterviewsRequest)(nil),         // 7: interview.ListInterviewsRequest
	(*ListInterviewsResponse)(nil),        // 8: interview.ListInterviewsResponse
	(*GetFeedbackRequest)(nil),            // 9: interview.GetFeedbackRequest
	(*GetFeedbackByInterviewRequest)(nil), // 10: interview.GetFeedbackByInterviewRequest
	(*CreateFeedbackRequest)(nil),         // 11: interview.CreateFeedbackRequest
	(*UpdateFeedbackRequest)(nil),         // 12: interview.UpdateFeedbackRequest
	(*GetPortfolioRequest)(nil),           // 13: interview.GetPortfolioRequest
	(*CreatePortfolioRequest)(nil),        // 14: interview.CreatePortfolioRequest
	(*UpdatePortfolioRequest)(nil),        // 15: interview.UpdatePortfolioRequest
	(*ListPortfoliosRequest)(nil),         // 16: interview.ListPortfoliosRequest
	(*ListPortfoliosResponse)(nil),        // 17: interview.ListPortfoliosResponse
}
var file_proto_interview_proto_depIdxs = []int32{
	0,  // 0: interview.ListInterviewsResponse.interviews:type_name -> interview.Interview
	2,  // 1: interview.ListPortfoliosResponse.portfolios:type_name -> interview.Portfolio
	3,  // 2: interview.InterviewService.GetInterview:input_type -> interview.GetInterviewRequest
	4,  // 3: interview.InterviewService.CreateInterview:input_type -> interview.CreateInterviewRequest
	5,  // 4: interview.InterviewService.UpdateInterview:input_type -> interview.UpdateInterviewRequest
	6,  // 5: interview.InterviewService.UpdateInterviewStatus:input_type -> interview.UpdateInterviewStatusRequest
	7,  // 6: interview.InterviewService.ListInterviews:input_type -> interview.ListInterviewsRequest
	9,  // 7: interview.FeedbackService.GetFeedback:input_type -> interview.GetFeedbackRequest
	10, // 8: interview.FeedbackService.GetFeedbackByInterview:input_type -> interview.GetFeedbackByInterviewRequest
	11, // 9: interview.FeedbackService.CreateFeedback:input_type -> interview.CreateFeedbackRequest
	12, // 10: interview.FeedbackService.UpdateFeedback:input_type -> interview.UpdateFeedbackRequest
	13, // 11: interview.PortfolioService.GetPortfolio:input_type -> interview.GetPortfolioRequest
	14, // 12: interview.PortfolioService.CreatePortfolio:input_type -> interview.CreatePortfolioRequest
	15, // 13: interview.PortfolioService.UpdatePortfolio:input_type -> interview.UpdatePortfolioRequest
	16, // 14: interview.PortfolioService.ListPortfolios:input_type -> interview.ListPortfoliosRequest
	0,  // 15: interview.InterviewService.GetInterview:output_type -> interview.Interview
	0,  // 16: interview.InterviewService.CreateInterview:output_type -> interview.Interview
	0,  // 17: interview.InterviewService.UpdateInterview:output_type -> interview.Interview
	0,  // 18: interview.InterviewService.UpdateInterviewStatus:output_type -> interview.Interview
	8,  // 19: interview.InterviewService.ListInterviews:output_type -> interview.ListInterviewsResponse
	1,  // 20: interview.FeedbackService.GetFeedback:output_type -> interview.Feedback
	1,  // 21: interview.FeedbackService.GetFeedbackByInterview:output_type -> interview.Feedback
	1,  // 22: interview.FeedbackService.CreateFeedback:output_type -> interview.Feedback
	1,  // 23: interview.FeedbackService.UpdateFeedback:output_type -> interview.Feedback
	2,  // 24: interview.PortfolioService.GetPortfolio:output_type -> interview.Portfolio
	2,  // 25: interview.PortfolioService.CreatePortfolio:output_type -> interview.Portfolio
	2,  // 26: interview.PortfolioService.UpdatePortfolio:output_type -> interview.Portfolio
	17, // 27: interview.PortfolioService.ListPortfolios:output_type -> interview.ListPortfoliosResponse
	15, // [15:28] is the sub-list for method output_type
	2,  // [2:15] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_interview_proto_init() }
func file_proto_interview_proto_init() {
	if File_proto_interview_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_interview_proto_rawDesc), len(file_proto_interview_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_interview_proto_goTypes,
		DependencyIndexes: file_proto_interview_proto_depIdxs,
		MessageInfos:      file_proto_interview_proto_msgTypes,
	}.Build()
	File_proto_interview_proto = out.File
	file_proto_interview_proto_goTypes = nil
	file_proto_interview_proto_depIdxs = nil
}
